### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by reinzor** [tuw-robotics/marker_msgs#2]
Will this package be released for Noetic anytime soon?

**Comment by maxbader** [comment]
I just pushed a noetic version. No code adaptation was needed. you can just pull the noetic-devel branch

**Comment by maxbader** [comment]
I you find any troubles please let me know

**Comment by reinzor** [comment]
Great thanks!

**Comment by reinzor** [comment]
Hi, 

Still cannot find a release in `Noetic`: `dpkg -l | grep noetic-marker-msgs` shows no result. Any updates on the status?
